djangoProject_saita/urls.py
from django.contrib import admin
from django.urls import path, include
from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('kino/', views.Kino_list.as_view(), name='allkino'),
    path('kino/<slug:pk>/<str:title>', views.Kino_detail.as_view(), name='info_movie'),

    path('actor/', views.Actor_list.as_view(), name='allactor'),
    path('actor/<slug:pk>/<str:lname>', views.Actor_detail.as_view(), name='info_actor'),

    path('director/', views.Director_list.as_view(), name='alldirector'),
    path('director/<slug:pk>/<str:lname>', views.Director_detail.as_view(), name='info_director'),
    # path('kino/<int:id>/', views.info, name='info'),
    path('user/', include('django.contrib.auth.urls')), # чтобы юзеры могли заходить на сайт в кабинет за счет переадресации include
    path('status/', views.status, name='status'),
    path('status/prosmotr/<int:id1>/<int:id2>/<int:id3>', views.prosmotr, name='prosmotr'),
    path('status/buy/<int:type>/', views.buy, name='buystatus'),
    path('user/registr/', views.registr, name='registr'),
    path('status/purchase/', views.purchase, name='purchase'),
    path('status/del/<int:t1>/', views.del_, name='del_'),
    path('status/app/<int:type_>/', views.app_, name='app_')
]

catalog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20, verbose_name='Жанр')

    def __str__(self):
        return self.name

class Director(models.Model):
    fname = models.CharField(max_length=20, verbose_name='')
    lname = models.CharField(max_length=20, verbose_name='')

    def __str__(self):
        return f'{self.lname} {self.fname}'

    def get_absolute_url(self): # автоматически формировка пути
        return reverse('info_director', args=[self.id, self.lname])

class Actor(models.Model):
    fname = models.CharField(max_length=20, verbose_name='Имя')
    lname = models.CharField(max_length=20, verbose_name='Фамилия')
    born = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    country = models.CharField(max_length=20, verbose_name='Страна')

    def __str__(self):
        return self.lname

    def get_absolute_url(self): # автоматически формировка пути
        return reverse('info_actor', args=[self.id, self.lname])

class Status(models.Model):
    VIBOR = (('Бесплатно', 'Бесплатно'), ('Базовая', 'Базовая'), ('Супер', 'Супер'))
    name = models.CharField(max_length=20, choices=VIBOR, verbose_name='Подписка')

    def __str__(self):
        return self.name

class Country(models.Model):
    name = models.CharField(max_length=20, verbose_name='Страна')

    def __str__(self):
        return self.name

class AgeRate(models.Model):
    choise = (('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'))
    rate = models.CharField(max_length=20, choices=choise, verbose_name='Рейтинг')

    def __str__(self):
        return self.rate

class Kino(models.Model):
    title = models.CharField(max_length=40, verbose_name='Название')
    genre = models.ForeignKey(Genre, on_delete=models.SET_DEFAULT, default=1, verbose_name='Жанр')
    rating = models.FloatField(verbose_name='Оценка')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    director = models.ForeignKey(Director, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, verbose_name='Описание')
    year = models.IntegerField()
    ager = models.ForeignKey(AgeRate, on_delete=models.SET_NULL, null=True)
    actor = models.ManyToManyField(Actor, verbose_name='Актеры')
    status = models.ForeignKey(Status, on_delete=models.SET_DEFAULT, default=1)
    image = models.CharField(max_length=100, blank=True, null=True, verbose_name='Картинки')

    def __str__(self):
        return self.title

    def display_actors(self):
        res = ''
        for a in self.actor.all():
            res += a.lname + ' '
        return res
    display_actors.short_description='Актеры'


    def get_absolute_url(self): # автоматически формировка пути
        return reverse('info_movie', args=[self.id, self.title])

templates/buy.html
{%  extends 'index.html' %}

{% block content %}
    <h2>Вы получили подписку: {{ podpiska }}.</h2>
{% endblock content %}

templates/del_.html
{%  extends 'index.html' %}

{% block content %}
    <h2>Вы удалили подписку {{ podpiska }}.</h2>
{% endblock content %}

templates/index.html
<!DOCTYPE html>  {# эта страница по сути является базовым шаблоном #}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block head %}{# джанговская тема для вывода информации head, то для того чтобы менять информацию которая формируется в функциях во views.py #}
        <title>Кино</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% endblock head %}
</head>
<body style="background-image: {% static 'img/main.png' %}">

{% block menu %}  {# джанговская тема для выбода меню, чтобы информация их функций views.py попадала на HTML #}{#    <nav class="container mt-3">#}
    {% include 'includes/nav.html' %}
{% endblock menu %}{# конец блока меню, пишется обязательно #}

    {% block content %}{# джанговская тема для вывода инфы в блок из питоновского файла views.py #}c
        <div class="container-fluid" style="margin-top: 30px">
            <h1 style="color: brown"><span class="badge bg-secondary">Привет, <span style="color: dodgerblue">{{ user_f_name }} {{ user_l_name }}!</span></span></h1>
            <h2>Предлагаем твоему вниманию!</h2>
            <h2>Каталог фильмов:</h2>
{#            <hr>#}
            <h3>У нас на сайте ты найдешь! </h3>
            <h3><span style="color: red">{{ k1 }}</span> фильма/ов,</h3>
            <h3><span style="color: red">{{ k2 }}</span> актера/ов,</h3>
            <h3><span style="color: red">{{ k3 }}</span> фильма/ов бесплатно.</h3>
        </div>
    {% endblock content %}


</body>
</html>





{#<!DOCTYPE html>  {# эта страница по сути является базовым шаблоном #}
{#{% load static %}#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    {% block head %}{# джанговская тема для вывода информации head, то для того чтобы менять информацию которая формируется в функциях во views.py #}
{#    <title>Кино</title>#}
{#        <link rel="stylesheet" href="{% static 'css/main.css' %}">#}
{#    {% endblock head %}#}
{#</head>#}
{#<body>#}
{#    {% block menu %}  {# джанговская тема для выбода меню, чтобы информация их функций views.py попадала на HTML #}
{#    <div class="menu" class="container mt-3">#}
{#        <a href="{% url 'home' %}">Главная</a> {# ссылки с путем по джанговской теме в {% путь который попадает в urls.py по имени %} #}
{#        <a href="{% url 'allkino' %}">Фильмы</a>#}
{#        <a href="{% url 'allactor' %}">Актеры</a>#}
{#        <a href="{% url 'alldirector' %}">Режиссеры</a>#}
{#        <a href="{% url 'status' %}">Подписка</a>#}
{#        {% if not user.username %}#}
{#        <a href="{% url 'login' %}">Логин</a>#}
{#            {% else %}#}
{#        <a href="{% url 'logout' %}">Выйти</a>#}
{#        {% endif %}#}
{#        <a href="{% url 'admin:index' %}">Кабинет администратора</a>#}
{#    </div>#}
{#    {% endblock menu %}{# конец блока меню, пишется обязательно #}
{##}
{#    {% block content %}{# джанговская тема для вывода инфы в блок из питоновского файла views.py #}
{#        <h1>Привет, {{ username }}!</h1>#}
{#        <h2>Каталог фильмов:</h2>#}
{#            <h3>На сайте {{ k1 }} фильма/ов</h3>#}
{#            <h3>На сайте {{ k2 }} актера/ов</h3>#}
{#            <h3>На сайте {{ k3 }} фильма/ов бесплатно</h3>#}
{#    {% endblock content %}#}
{##}
{#</body>#}
{#</html>#}

templates/podpiska.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    {% block head %}
        <title>Все фильмы</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/podpiska.css' %}">

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    {% endblock head %}
    <div class="container-fluid" style="margin-top: 30px">
    <h2><span class="badge bg-secondary">Подписки</span></h2>

    {% for one in podpiska %}
        <h3  style="color: red" class="main">{{ one.name }}</h3>
        <div class="cont">
        {% for kino in one.kino_set.all  %}
            <div class="card">
                <img src="{% static kino.image %}" alt="">
            <h4>{{ kino.title }}</h4>
            <h6>{{ kino.genre }}</h6>

                {% if not user.username %}
                <a href="{% url 'prosmotr' kino.id one.id 0 %}">
                    <button type="button" class="btn btn-primary">Смотреть</button></a>
                {% else %}
                <a href="{% url 'prosmotr' kino.id one.id user.id %}">
                    <button type="button" class="btn btn-primary">Смотреть</button></a>
            {% endif %}
                </div>
            {% endfor %}
        </div>
        {% endfor %}
    <img src="{% static 'img/django.png'%} }}" alt="">
    </div>
{% endblock content%}

templates/prosmotr.html
{% extends 'index.html' %}
{% load static %}
    {% block head %}{# джанговская тема для вывода информации head, то для того чтобы менять информацию которая формируется в функциях во views.py #}
        <title>Кино</title>
        <link rel="stylesheet" href="{% static 'css/prosmotr.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% endblock head %}

{% block content %}
    <h3><span class="badge bg-secondary">Фильм: {{ kino }}</span></h3>

        <h3>Ваша подписка {{ status }}.</h3>
    <h3>Подписка фильма {{ statuskino }}.</h3>

        {% if prava %}
    <h4>Приятного просмотра</h4>
    {% else %}
        <h4><span class="badge bg-secondary">Чтобы просмотреть фильм, необходимо приобрести подписку {{ statuskino }}</span></h4>
    {% endif %}

    {% if not prava %}
        {% if user.username %}
    <h4>
        <a href="{% url 'buystatus' type=2 %}">Купить базовую подписку</a>
    </h4>

    <h4>
        <a href="{% url 'buystatus' type=3 %}">Купить подписку супер</a>
    </h4>
            {% else %}
                <h4>
        <a href="{% url 'login' %}">Купить базовую подписку</a>
    </h4>

    <h4>
        <a href="{% url 'login' %}">Купить подписку супер</a>
    </h4>
            {% endif %}
    {% endif %}


{% endblock content %}

templates/purshase.html
{% extends 'index.html' %}  {#копия из другого файла#}
{% block content %}
    {% csrf_token %}

    {% if quantity == 1 %}
        <div style="color: darkblue; padding-left: 35px" >
            <h2>У вас сейчас {{ quantity }} подписка.</h2>
            <h2>Сейчас ваша подписка {{ podpiska }}</h2>
        </div>
        <table>
        <ul>
            <h4><a style="color: red"  href="{% url 'del_' t1=podpiska.id %}">Отказаться от подписки {{ podpiska }}</a></h4>
            <h4>
                <a href="{% url 'app_' type_=2 %}">Получить подписку Базовая</a>
            </h4>

            <h4>
                <a href="{% url 'app_' type_=3 %}">Получить подписку Супер</a>
            </h4>
        </ul>
        </table>
    {% elif quantity == 2 %}
        <div style="color: darkblue; padding-left: 35px" >
            <h2>У вас сейчас {{ quantity }} подписки.</h2>
            <h2>Сейчас ваши подписки {{ podpiska }} и {{ podpiska2 }}.</h2>
        </div>
        <table>
        <ul>
            <h4><a style="color: red"  href="{% url 'del_' t1=podpiska.id  %}">Отказаться от подписки  {{ podpiska }}</a></h4>
            <h4><a style="color: red"  href="{% url 'del_' t1=podpiska.id  %}">Отказаться от подписки  {{ podpiska2 }}</a></h4>
            <h4>
                <a href="{% url 'app_' type_=3 %}">Получить подписку Супер</a>
            </h4>
        </ul>
        </table>
    {% elif quantity == 3 %}
        <div style="color: darkblue; padding-left: 35px" >
            <h2>У вас сейчас {{ quantity }} подписки.</h2>
            <h2>Сейчас ваши подписки {{ podpiska }}, {{ podpiska2 }} и {{ podpiska3 }}.</h2>
        </div>
        <table>
        <ul>
            <h4><a style="color: red" href="{% url 'del_' t1=podpiska.id  %}">Отказаться от подписки  {{ podpiska }}</a></h4>
            <h4><a style="color: red"  href="{% url 'del_' t1=podpiska.id  %}">Отказаться от подписки  {{ podpiska2 }}</a></h4>
            <h4><a style="color: red"  href="{% url 'del_' t1=podpiska.id  %}">Отказаться от подписки  {{ podpiska3 }}</a></h4>
        </ul>
        </table>
    {% else %}
        <div style="color: darkblue; padding-left: 35px" >
        <h2>{{ none }}</h2>
        </div>
        <table>
            <ul>
{#                <li><a href="">Подписаться на подписку</a></li>#}
            <h4>
                <a href="{% url 'app_' type_=1 %}">Получить подписку Бесплатная</a>
            </h4>

            <h4>
                <a href="{% url 'app_' type_=2 %}">Получить подписку Базовая</a>
            </h4>

            <h4>
                <a href="{% url 'app_' type_=3 %}">Получить подписку Супер</a>
            </h4>
            </ul>
        </table>
    {% endif %}


{% endblock content %}